### ISSUE TITLE
要是能让管理员和群主都能参与就好了

### ISSUE THREAD

**Issue by yaoxiaosa** [MrXiaoM/WifeYouWant#4]
QWQ现在管理员群主发指令没反应

**Comment by MrXiaoM** [comment]
我除了增加 NormalMember 检查禁止了匿名成员使用和黑白名单以外，几乎没加限制。按理群主和管理员都是能用的，在插件发布之后我群管理员也能正常使用插件，希望能提供更多细节。

**Comment by yaoxiaosa** [comment]
阿哲，我这破浏览器，issue发错人了

**Comment by yaoxiaosa** [comment]
谢谢大佬，俺群友刚才回复说以前见过的抽老婆插件是可以在今天聊过天的人里抽取老婆的，刚才测试了一下，1000人的群抽的基本都是潜水的哈哈哈哈哈
