### ISSUE TITLE
设置不明白

### ISSUE THREAD

**Issue by wvuda** [MrXiaoM/WifeYouWant#5]
有办法设置成只有活跃的或者近期群里说过话的人才能抽取吗

**Comment by MrXiaoM** [comment]
目前插件没有这个功能，等我有空更新插件或者有人 PR 再说

**Comment by wvuda** [comment]
行，等

**Comment by wvuda** [comment]
设置里这三个怎样算开了啊
![U9NKGB32IZ(CRA1ZJ}AJOIG](https://user-images.githubusercontent.com/109006153/183885587-9c03e2e9-2474-4170-b4d1-87577c1730b1.png)

**Comment by MrXiaoM** [comment]
> 设置里这三个怎样算开了啊
> ![U9NKGB32IZ(CRA1ZJ}AJOIG](https://user-images.githubusercontent.com/109006153/183885587-9c03e2e9-2474-4170-b4d1-87577c1730b1.png)
> 
>

我个人认为 yaml 基础知识没必要在这里说

**Comment by MrXiaoM** [comment]
0.1.3 已更新
