### ISSUE TITLE
希望可以增加活跃群员限制

### ISSUE THREAD

**Issue by kanoucy** [MrXiaoM/WifeYouWant#7]
抽到的全是潜水的。。我看有active-member-only 和member-active-time 两个参数 可以添加进去yml生效嘛？

**Comment by MrXiaoM** [comment]
目前不能，那个功能我是从别人的 folk 里拉取的，因为没有其他我自己的更新没好意思发版。最近我在忙别的项目，如果你急着要用的话可以先自行构建插件。

**Comment by MrXiaoM** [comment]
0.1.3 已更新
