### ISSUE TITLE
换老婆后，新老婆的昵称还是上一个老婆的昵称

### ISSUE THREAD

**Issue by Algar233** [MrXiaoM/WifeYouWant#8]
头像和QQ号都换了，只有昵称没换

**Comment by MrXiaoM** [comment]
但是插件只存了qq号和时间，其他信息都是执行命令时现取的，理论上应该不会出现这个问题才是

**Comment by Algar233** [comment]
那就很奇怪🤔日志里也没有报错![image](https://user-images.githubusercontent.com/57739158/197452173-da1466bb-7cd9-4846-ae3a-9dca043e61d5.jpeg)

**Comment by MrXiaoM** [comment]
把配置文件里 messages-change-wife 的 `$old_wife_namecard` 替换成 `$wife_namecard` 试试。
