### ISSUE TITLE
希望可以限制换老婆次数，或者过一段时间撤回换老婆的信息

### ISSUE THREAD

**Issue by smoadrareun** [MrXiaoM/WifeYouWant#9]
在开启换老婆之后消息容易刷屏，希望能新增限制次数的功能，或者在110秒的时间自动撤回换老婆的信息

**Comment by MrXiaoM** [comment]
加了冷却时间和自动撤回。
由于数据储存设计得太屎了，要加每日限制次数比较困难，所以没有加
